[package]
name = "arrakis"
version = "0.1.0"
authors = ["JP Moresmau"]
edition = "2018"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.138", features = ["derive"] }

[dependencies.amethyst]
version = "0.15.3"
features = ["vulkan"]
