[package]
name = "arrakis"
version = "0.1.0"
authors = ["JP Moresmau"]
edition = "2018"

[dependencies]
rand = "0.7.2"
serde = { version = "1.0.101", features = ["derive"] }

[dependencies.amethyst]
version = "0.12"
features = ["vulkan"]
